"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _route_shell from './route-shell.bones.json'

configureBoneyard({"color":"#1f2937","darkColor":"#111827","animate":"shimmer","shimmerColor":"#374151","darkShimmerColor":"#1f2937","speed":"1.6s"})

registerBones({
  "route-shell": _route_shell,
})
